### ISSUE TITLE
MX Linux 21.1 - Could not install *.deb - Unknown Compression

### ISSUE THREAD

**Issue by StevenAlexander44** [luisrguerra/monday-icon-theme#1]
```
$ sudo dpkg -i Downloads/monday-icon-theme-v0.3.1.deb 
dpkg-deb: error: archive 'Downloads/monday-icon-theme-v0.3.1.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive Downloads/monday-icon-theme-v0.3.1.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 Downloads/monday-icon-theme-v0.3.1.deb
```

**Comment by luisrguerra** [comment]
I don't know where this error comes from, the compression method is the default, maybe in MX linux the deb package systems are outdated

**Comment by StevenAlexander44** [comment]
I just ended up cloning it and used the install script (thanks for the icons)

I've never encountered it before, but who knows what the issue is.
If anyone in the future cares: `Debian 'dpkg' package management program version 1.20.12 (amd64).`
